model_list:
  - model_name: gpt120
    litellm_params:
      model: openrouter/openai/gpt-oss-120b

  - model_name: mini
    litellm_params:
      model: openai/gpt-5.4-mini


router_settings:
  num_retries: 2
  allowed_fails: 3
  cooldown_time: 30
  routing_strategy: simple-shuffle
  fallbacks:
    - "*": ["mini"]
  # routing_strategy: least-busy
  # routing_strategy: usage-based-routing
  # routing_strategy: usage-based-routing-v2
  # routing_strategy: latency-based-routing
  # routing_strategy: cost-based-routing

